language: php

git:
  depth: 1

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --prefer-dist --no-autoloader

script:
  - vendor/bin/phpcs Bundles --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -p

notifications:
  email: false
